DZEN2_BACKGROUND: '#252525'
DZEN2_FOREGROUND: '#eceff4'
DZEN2_HIGHLIGHT_BG: '#353535'
DZEN2_HIGHLIGHT_FG: '#cd96e5'
DZEN2_FONTNAME: 'Tamzen:pixelsize=15'

DZEN2_WIDTH_OFFSET: 8
DZEN2_X_OFFSET: 4
DZEN2_Y_OFFSET: 4
DZEN2_HEIGHT: 26
